### ISSUE TITLE
Labeling of persons

### ISSUE THREAD

**Issue by aysterberi** [aysterberi/ThesisProject#1]
If remove a folder "in the middle" of the directory structure, the next person you create will have the wrong label. Not super important, since it's only concept right now.

**Comment by aysterberi** [comment]
Fixed somewhat. There are still problems with labeling if you create and empty directory, and then create a new person which you add pictures to. Perhaps this could be solved by adding persons/labels only when you add pictures to the person.

**Comment by Grusburk** [comment]
Think its solved but its very funky
